#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import cmd
import os

class MDManager(cmd.Cmd):

  currentDB = None

  def __init__(self):
    cmd.Cmd.__init__(self)
    self.prompt = 'MoonDocks db Manager ❯ '
    self.intro = '''

    Welcome to the MoonDocks Database Manager (mddb)

    '''
  #################################################
  # Command definitions
  #################################################

  ## Database commands

  def do_open(self, args):
    '''Opens a database'''
    print('Opening db: ')


  ## Core commands

  def do_exit(self, args):
    '''Exit MoonDocks db Manager'''
    return -1

  def do_EOF(self, args):
    '''Exit on system EOF character'''
    return self.do_exit(args)

  def do_shell(self, args):
    '''Pass command to the system shell when the line begins with `!`'''
    os.system(args)

  def do_help(self, args):
    '''Get help for commands
        `help` or `?` with no arguments prints a list of commands
        `help «command»` or `? «command»` gives help on «command»
    '''
    cmd.Cmd.do_help(self, args)

  #################################################
  # Override Cmd object methods
  #################################################

  def preloop(self):
    '''Initialization before prompting user for commands.'''
    cmd.Cmd.preloop(self)
    self._hist    = []
    self._locals  = {}
    self._globals = {}

  def postloop(self):
    '''Do any necessary cleanup.'''
    cmd.Cmd.postloop(self)
    print('Closing MoonDocks db Manager...')


if __name__ == '__main__':
  mdmanager = MDManager()
  mdmanager.cmdloop()
